### ISSUE TITLE
Нет сообщения о неверном ответе

### ISSUE THREAD

**Issue by uzarsalan** [SESEGGARMAEVA/hw_2#2]
https://github.com/SESEGGARMAEVA/hw_2/blob/f0671997af034aad8a641583d22706e8e80c55f5/indexif.html#L15

Если человек отвечает неверно, то ему не выводится никакого сообщения и он не поймет что ответил неверно. Нужно добавить сообщение об ошибке в else

**Comment by SESEGGARMAEVA** [comment]
Исправила.

**Comment by uzarsalan** [comment]
В первом вопросе нет сообщения при неверном ответе

**Comment by SESEGGARMAEVA** [comment]
Исправила.
