### ISSUE TITLE
Невыполнимое условие

### ISSUE THREAD

**Issue by uzarsalan** [SESEGGARMAEVA/hw_2#3]
https://github.com/SESEGGARMAEVA/hw_2/blob/f0671997af034aad8a641583d22706e8e80c55f5/indexif.html#L29

Два предыдущих условия полностью перекрывают все возможные варианты, поэтому else никогда не выполнится и смысла в нем нет

**Comment by SESEGGARMAEVA** [comment]
Исправила.
