### ISSUE TITLE
Запятая после последнего элемента

### ISSUE THREAD

**Issue by uzarsalan** [SESEGGARMAEVA/hw_2#4]
https://github.com/SESEGGARMAEVA/hw_2/blob/4fa37505cb68d06539248e99a773d6a0e42f80b0/indexjs.html#L10

Если ты ставишь запятую после последнего элемента массива, то js думает что там есть еще один элемент, просто он пустой. Чтобы все было точно, запятые после последнего элемента ставить не нужно

**Comment by SESEGGARMAEVA** [comment]
Исправила.
