### ISSUE TITLE
Ты проверяла что выводится в консоли?

### ISSUE THREAD

**Issue by uzarsalan** [SESEGGARMAEVA/hw_2#5]
https://github.com/SESEGGARMAEVA/hw_2/blob/4fa37505cb68d06539248e99a773d6a0e42f80b0/indexcycles.html#L65

Тут есть ошибка и она не даст выполнится программе. Обязательно проверяй что выводится у тебя в результате)

**Comment by SESEGGARMAEVA** [comment]
Исправила. Проверила в консоли.
